#!/bin/zsh

setopt NO_CLOBBER
setopt INTERACTIVE_COMMENTS
setopt HASH_EXECUTABLES_ONLY
setopt EXTENDED_GLOB
setopt GLOB_STAR_SHORT
setopt NUMERIC_GLOB_SORT

# setopt ALWAYSTOEND
# setopt APPENDHISTORY
# setopt AUTOCD
# setopt AUTOLIST
# setopt AUTOMENU
# setopt AUTOPUSHD
# setopt COMPLETEALIASES
# setopt COMPLETEINWORD
# setopt EXTENDEDHISTORY
# setopt HISTFINDNODUPS
# setopt HISTIGNOREALLDUPS
# setopt HISTREDUCEBLANKS
# setopt HISTSAVENODUPS
# setopt HISTIGNORESPACE
# setopt INCAPPENDHISTORY
# setopt NOMATCH
# setopt NOTIFY
# setopt PROMPTSUBST
# setopt PUSHDIGNOREDUPS
# setopt PUSHDMINUS
# setopt PUSHDSILENT
# setopt PUSHDTOHOME
# setopt SHAREHISTORY

# unsetopt BEEP
# unsetopt MENUCOMPLETE
